/* See Project CHIP LICENSE file for licensing information. */

/**
 *    @file
 *          Platform-specific configuration overrides for CHIP on
 *          the STM32 platform.
 */

#pragma once

#ifndef CHIP_PLATFORM_CONFIG_H
#define CHIP_PLATFORM_CONFIG_H

// ==================== General Platform Adaptations ====================

#define CHIP_CONFIG_PERSISTED_STORAGE_ENC_MSG_CNTR_ID "enc-msg-counter"
// The STM32 NVS implementation limits key names to 15 characters.
#define CHIP_CONFIG_PERSISTED_STORAGE_MAX_KEY_LENGTH 16

#define CHIP_LOG_FILTERING 0

#define CHIP_CONFIG_ABORT() abort()

// ==================== Security Adaptations ====================

#define CHIP_CONFIG_USE_OPENSSL_ECC 0
#define CHIP_CONFIG_USE_MICRO_ECC 0

#define CHIP_CONFIG_HASH_IMPLEMENTATION_OPENSSL 0
//#define CHIP_CONFIG_HASH_IMPLEMENTATION_MINCRYPT 1

#define CHIP_CONFIG_RNG_IMPLEMENTATION_OPENSSL 0
#define CHIP_CONFIG_RNG_IMPLEMENTATION_CHIPDRBG 1

#define CHIP_CONFIG_AES_IMPLEMENTATION_OPENSSL 0
#define CHIP_CONFIG_AES_IMPLEMENTATION_AESNI 0
//#define CHIP_CONFIG_AES_IMPLEMENTATION_PLATFORM 1

#define CHIP_CONFIG_SUPPORT_PASE_CONFIG0 0
#define CHIP_CONFIG_SUPPORT_PASE_CONFIG1 0
#define CHIP_CONFIG_SUPPORT_PASE_CONFIG2 0
#define CHIP_CONFIG_SUPPORT_PASE_CONFIG3 0
#define CHIP_CONFIG_SUPPORT_PASE_CONFIG4 1

#define CHIP_CONFIG_ENABLE_KEY_EXPORT_INITIATOR 0

#define CHIP_CONFIG_ENABLE_PROVISIONING_BUNDLE_SUPPORT 0

#define CHIP_DEVICE_CONFIG_DYNAMIC_ENDPOINT_COUNT 8


#define CHIP_CONFIG_MAX_UNSOLICITED_MESSAGE_HANDLERS 8 //CONFIG_MAX_UNSOLICITED_MESSAGE_HANDLERS

#define CHIP_CONFIG_MAX_EXCHANGE_CONTEXTS 8 //CONFIG_MAX_EXCHANGE_CONTEXTS

#define CHIP_CONFIG_ENABLE_SERVER_IM_EVENT 1

#endif /* CHIP_PLATFORM_CONFIG_H */
